# Generated by Django 6.0.2 on 2026-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cca2', models.CharField(blank=True, max_length=2, null=True)),
                ('capital', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
